version: '3.9'

services:

  frontend:
    build: frontend
    ports:
      - 8080:80
    volumes:
      - ./:/app

  backend:
    build: backend
    ports:
      - 8081:80
    volumes:
      - ./:/app

  mysql_dev:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=apple_worm
      - MYSQL_DATABASE=apple_dev
      - MYSQL_USER=apple_user
      - MYSQL_PASSWORD=apple_red
    ports:
      - 3306:3306
    volumes:
      - ./mysql_dev_cache:/var/lib/mysql